const boundedExecutorChecks = {
  "configured-role": null,
  "tool-mount": null,
  "tool-umount": null,
  "invocation-root": null,
  "invocation-parent": null,
  "resource-journal": null,
  "storage-allocation": null,
  "storage-ancestor": null,
  "storage-parent": null,
  "storage-root": null,
  "storage-tmpfs": null,
  "storage-propagation-set": null,
  "storage-propagation": null,
  "storage-layout": null,
  "storage-artifact-mount": null,
  "storage-run-mounts": null,
  "invocation-directory": null,
  "invocation-mount": null,
  "storage-verification": null
};

export const schema = {
  "scopes": {
    "startup": {
      "configuration": null,
      "enclave-preparation": null,
      "network-enforcement": null,
      "compose-configuration": null,
      "infrastructure": null,
      "gateway-attachment": null,
      "github-attachment": null,
      "github-ready": null,
      "gateway-ready": null,
      "delegation": null,
      "readiness": null
    },
    "gateway-attachment": {
      "contract": null,
      "identity": null,
      "network-connect": null,
      "network-membership": null
    },
    "gateway-handshake": {
      "contract": null,
      "initialize": null,
      "initialized": null,
      "tools-list": null
    },
    "enclave-runtime": {
      "primary-runtime": null,
      "script-runtime": null,
      "agent-runtime": null,
      "host-service": null
    },
    "enclave-storage": {
      "private-root-isolation": null,
      "work-directory": null,
      "directory-layout": null,
      "run-identity": null,
      "seed-catalog": null,
      "capability-staging": null,
      "github-identity": null,
      "delegation-custody": null
    },
    "host-isolation": {
      "journal-isolation": null,
      "invocation-isolation": null,
      "allocation-isolation": null
    },
    "provider-selection": {
      "storage-provider": null
    },
    "storage-admission": {
      "root": null,
      "runner-eligibility": null,
      "ubuntu-distribution": null,
      "mount-capability": null,
      "tmpfs-support": null,
      "kvm-access": null,
      "kvm-device": null,
      "kvm-open": null,
      "cgroup-writable": null,
      "cgroup-controllers": null
    },
    "bounded-runtime": {
      ...boundedExecutorChecks,
      "operator-identity": null,
      "artifact-configuration": null,
      "cloud-hypervisor-trust": null,
      "virtiofsd-trust": null,
      "tool-getent": null,
      "tool-getfacl": null,
      "tool-groupdel": null,
      "tool-id": null,
      "tool-ip": null,
      "tool-nft": null,
      "tool-sysctl": null,
      "tool-flock": null,
      "tool-mke2fs": null,
      "tool-debugfs": null,
      "tool-e2fsck": null,
      "tool-rsync": null,
      "tool-setfacl": null,
      "tool-setpriv": null,
      "tool-useradd": null,
      "tool-userdel": null,
      "kernel-trust": null,
      "rootfs-trust": null,
      "supervisor-trust": null,
      "manifest-trust": null,
      "bundle-trust": null,
      "artifact-snapshot": null,
      "snapshot-journal": null,
      "tool-gh": null,
      "manifest-attestation": null,
      "manifest-contents": null,
      "cloud-hypervisor-digest": null,
      "virtiofsd-digest": null,
      "cloud-hypervisor-version": null,
      "virtiofsd-version": null,
      "kernel-digest": null,
      "rootfs-digest": null,
      "supervisor-digest": null,
      "platform": null,
      "architecture": null,
      "kvm-access": null,
      "kvm-group": null,
      "host-policy": null,
      "root": null,
      "ipv4-control": null,
      "ipv6-control": null,
      "seccomp-control": null,
      "cgroup-v2": null,
      "tool-docker": null,
      "docker-infrastructure": null,
      "docker-info": null,
      "docker-compose": null
    },
    "storage-verification": {
      "journal-identity": null,
      "mountinfo-read": null,
      "mountinfo-observation": null,
      "allocation-root": null,
      "invocation-state": null,
      "run-storage": null,
      "rootfs-preparation": null,
      "artifact-parent": null,
      "sealed-snapshot": null
    },
    "artifact-snapshot": {
      "root": null,
      "directory": null,
      "identity": null,
      "vmm-copy": null,
      "vmm-mode": null,
      "virtiofsd-copy": null,
      "virtiofsd-mode": null,
      "kernel-copy": null,
      "kernel-mode": null,
      "rootfs-copy": null,
      "rootfs-mode": null,
      "supervisor-copy": null,
      "supervisor-mode": null,
      "manifest-copy": null,
      "manifest-mode": null,
      "bundle-copy": null,
      "bundle-mode": null,
      "directory-mode": null,
      "mount-intent": null,
      "topology-before": null,
      "bind": null,
      "mount-capture": null,
      "readonly-exec": null,
      "sealed-storage": null,
      "partial-remove": null
    },
    "bounded-cleanup": {
      "storage-close": null,
      "directory-release": null,
      "journal-complete": null
    },
    "storage-mount-capture": {
      "canonical-path": null,
      "mountinfo-read": null,
      "mountinfo-parse": null,
      "mountinfo-topology": null,
      "match-count": null,
      "filesystem": null,
      "source": null,
      "journal-open": null,
      "journal-write": null,
      "journal-file-sync": null,
      "journal-file-close": null,
      "journal-publish": null,
      "journal-directory-sync": null,
      "journal-staging-remove": null
    },
    "bounded-artifacts": {
      ...boundedExecutorChecks,
      "tool-rsync": null,
      "verification-directory": null,
      "enclave-artifacts": null
    },
  },
  "optionalChecks": [
    "storage-verification/sealed-snapshot",
    "startup/github-attachment", "startup/github-ready", "startup/delegation",
    "enclave-runtime/script-runtime", "enclave-runtime/agent-runtime", "enclave-runtime/host-service",
    "enclave-storage/seed-catalog", "enclave-storage/github-identity", "enclave-storage/delegation-custody",
    "artifact-snapshot/manifest-copy", "artifact-snapshot/manifest-mode",
    "artifact-snapshot/bundle-copy", "artifact-snapshot/bundle-mode",
    "artifact-snapshot/partial-remove", "bounded-cleanup/directory-release"
  ],
  "reasons": {
    "none": null,
    "unknown": null,
    "requirement-not-met": null,
    "platform-unsupported": null,
    "architecture-unsupported": null,
    "github-actions-required": null,
    "runner-not-github-hosted": null,
    "ubuntu-image-required": null,
    "command-failed": null,
    "mount-noexec": null,
    "storage-mount-options": null,
    "storage-mount-propagation": null,
    "storage-path-changed": null,
    "storage-cap-changed": null,
    "mountinfo-malformed": null,
    "storage-mount-missing": null,
    "storage-mount-multiple": null,
    "storage-mount-filesystem": null,
    "storage-mount-source": null,
    "storage-identity-uncommitted": null,
    "storage-mount-identity-changed": null,
    "storage-mount-unrecorded": null,
    "rsync-file-io": null,
    "rsync-partial-transfer": null,
    "rsync-source-vanished": null,
    "path-not-absolute": null,
    "private-root-overlap": null,
    "mount-source-invalid": null,
    "ancestor-symlink": null,
    "ancestor-writable": null,
    "ancestor-owner": null,
    "file-symlink": null,
    "file-type": null,
    "file-writable": null,
    "file-owner": null,
    "tool-not-found": null,
    "version-format": null,
    "version-mismatch": null,
    "digest-format": null,
    "digest-empty": null,
    "digest-mismatch": null,
    "ENOENT": null,
    "EACCES": null,
    "EPERM": null,
    "ENOTDIR": null,
    "ELOOP": null,
    "ENOEXEC": null,
    "EISDIR": null,
    "ENOSPC": null,
    "EROFS": null,
    "EIO": null,
    "dns-not-found": null,
    "dns-temporary": null,
    "connection-refused": null,
    "connection-timeout": null,
    "request-timeout": null,
    "network-unreachable": null,
    "host-unreachable": null,
    "connection-reset": null,
    "transport-other": null,
    "http-auth": null,
    "http-status": null,
    "backend-unavailable": null,
    "response-too-large": null,
    "malformed-json": null,
    "malformed-protocol": null,
    "rpc-error": null,
    "identity-mismatch": null,
    "tools-mismatch": null,
    "readiness-deadline": null
  }
};
