/**
 * Generates the per-run guest entrypoint script AWF stages into the NVX
 * `custom` layer.
 *
 * The NVX guest contract is kernel-command-line only: `nvx_entrypoint=` takes a
 * single absolute path and each `nvx_arg=` token must be whitespace-free, and
 * there is no mechanism for passing environment variables. Writing the per-run
 * environment, working directory, and agent command into a script inside the
 * AWF-owned guest layer is therefore what makes `--env`/`--env-all`/
 * `--env-file` passthrough (and any agent command containing whitespace)
 * possible without changing the attested guest artifacts, and it keeps the
 * values off the kernel command line, which is visible in the host process
 * table.
 */

/** Shell metacharacter-free variable names are the only ones we will export. */
const SAFE_ENVIRONMENT_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;

export interface NvxGuestRunScriptOptions {
  /** Per-run guest environment, already free of real provider credentials. */
  readonly environment: Readonly<Record<string, string>>;
  /** Absolute guest directory the agent command runs in. */
  readonly workingDirectory: string;
  /** The agent command, executed with `/bin/sh -c`. */
  readonly command: string;
}

export function buildNvxGuestRunScript({
  environment,
  workingDirectory,
  command,
}: NvxGuestRunScriptOptions): string {
  if (!workingDirectory.startsWith('/')) {
    throw new Error(
      `NVX guest working directory must be absolute: ${workingDirectory}`,
    );
  }
  if (!command.trim()) {
    throw new Error('NVX guest run script requires a non-empty agent command');
  }
  const lines = [
    '#!/bin/sh',
    '# Generated by AWF for a single NVX one-shot microVM run. Do not edit.',
    'set -e',
  ];
  for (const name of Object.keys(environment).sort()) {
    if (!SAFE_ENVIRONMENT_NAME.test(name)) {
      throw new Error(`Unsafe NVX guest environment variable name: ${name}`);
    }
    const value = environment[name];
    assertNoNulByte(name, value);
    lines.push(`export ${name}=${quoteForShell(value)}`);
  }
  lines.push(`cd ${quoteForShell(workingDirectory)}`);
  lines.push(`exec /bin/sh -c ${quoteForShell(command)}`);
  return `${lines.join('\n')}\n`;
}

function assertNoNulByte(name: string, value: string): void {
  if (value.includes('\0')) {
    throw new Error(`NVX guest environment value for ${name} must not contain NUL`);
  }
}

/**
 * POSIX single-quote escaping: everything inside `'...'` is literal, and an
 * embedded `'` is emitted by closing the quote, escaping it, and reopening.
 */
function quoteForShell(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
