import { buildNvxGuestRunScript } from './guest-entrypoint';

describe('buildNvxGuestRunScript', () => {
  it('exports the per-run environment in sorted order before running the command', () => {
    const script = buildNvxGuestRunScript({
      environment: { HTTPS_PROXY: 'http://172.31.0.10:3128', AWF_RUNTIME: 'nvx' },
      workingDirectory: '/workspace',
      command: 'echo hello',
    });

    expect(script.split('\n')).toEqual([
      '#!/bin/sh',
      '# Generated by AWF for a single NVX one-shot microVM run. Do not edit.',
      'set -e',
      "export AWF_RUNTIME='nvx'",
      "export HTTPS_PROXY='http://172.31.0.10:3128'",
      "cd '/workspace'",
      "exec /bin/sh -c 'echo hello'",
      '',
    ]);
  });

  it('carries multi-word agent commands that a whitespace-free nvx_arg token cannot', () => {
    const script = buildNvxGuestRunScript({
      environment: {},
      workingDirectory: '/workspace/packages/app',
      command: 'copilot --allow-all-tools -p "fix the build"',
    });

    expect(script).toContain("cd '/workspace/packages/app'");
    expect(script).toContain(
      `exec /bin/sh -c 'copilot --allow-all-tools -p "fix the build"'`,
    );
  });

  it('escapes embedded single quotes with POSIX quote splicing', () => {
    const script = buildNvxGuestRunScript({
      environment: { MESSAGE: "it's fine" },
      workingDirectory: '/workspace',
      command: "echo 'done'",
    });

    expect(script).toContain(`export MESSAGE='it'\\''s fine'`);
    expect(script).toContain(`exec /bin/sh -c 'echo '\\''done'\\'''`);
  });

  it('rejects environment variable names that are not shell-safe', () => {
    expect(() => buildNvxGuestRunScript({
      environment: { 'BAD;NAME': 'x' },
      workingDirectory: '/workspace',
      command: 'true',
    })).toThrow(/Unsafe NVX guest environment variable name/);
  });

  it('rejects environment values containing NUL', () => {
    expect(() => buildNvxGuestRunScript({
      environment: { TOKEN: 'a\0b' },
      workingDirectory: '/workspace',
      command: 'true',
    })).toThrow(/must not contain NUL/);
  });

  it('rejects a relative working directory and an empty command', () => {
    expect(() => buildNvxGuestRunScript({
      environment: {},
      workingDirectory: 'workspace',
      command: 'true',
    })).toThrow(/must be absolute/);
    expect(() => buildNvxGuestRunScript({
      environment: {},
      workingDirectory: '/workspace',
      command: '   ',
    })).toThrow(/non-empty agent command/);
  });
});
