#!/usr/bin/env node

/**
 * AWF API Proxy Sidecar
 *
 * Node.js-based proxy that:
 * 1. Keeps LLM API credentials isolated from agent container
 * 2. Routes all traffic through Squid via HTTP_PROXY/HTTPS_PROXY
 * 3. Injects authentication headers (Authorization, x-api-key)
 * 4. Respects domain whitelisting enforced by Squid
 * 5. Validates an ephemeral per-job token on every non-health request
 */

const http = require('http');
const https = require('https');
const crypto = require('crypto');
const { URL } = require('url');
const { HttpsProxyAgent } = require('https-proxy-agent');
const { generateRequestId, sanitizeForLog, logRequest } = require('./logging');
const metrics = require('./metrics');
const rateLimiter = require('./rate-limiter');

// Create rate limiter from environment variables
const limiter = rateLimiter.create();

// Max request body size (10 MB) to prevent DoS via large payloads
const MAX_BODY_SIZE = 10 * 1024 * 1024;

// Headers that must never be forwarded from the client.
// The proxy controls authentication — client-supplied auth/proxy headers are stripped.
const STRIPPED_HEADERS = new Set([
  'host',
  'authorization',
  'proxy-authorization',
  'x-api-key',
  'forwarded',
  'via',
]);

/** Returns true if the header name should be stripped (case-insensitive). */
function shouldStripHeader(name) {
  const lower = name.toLowerCase();
  return STRIPPED_HEADERS.has(lower) || lower.startsWith('x-forwarded-');
}

// Read API keys from environment (set by docker-compose)
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const COPILOT_GITHUB_TOKEN = process.env.COPILOT_GITHUB_TOKEN;

// Ephemeral per-job proxy authentication token.
// Generated by the AWF CLI and shared with the agent container.
// When set, every non-health request must carry this token in x-api-key or
// Authorization: Bearer — otherwise the proxy rejects with HTTP 401.
// When not set, all non-health requests are rejected to enforce secure defaults.
const AWF_PROXY_TOKEN = process.env.AWF_PROXY_TOKEN || null;

/**
 * Extract the inbound credential token from the request.
 * Accepts either:
 *   - x-api-key: <token>            (Anthropic / OpenCode convention)
 *   - Authorization: Bearer <token> (OpenAI / Copilot convention)
 *
 * @param {import('http').IncomingMessage} req
 * @returns {string|null} The raw token string, or null if absent.
 */
function extractInboundToken(req) {
  const apiKey = req.headers['x-api-key'];
  if (typeof apiKey === 'string' && apiKey.length > 0) {
    return apiKey;
  }
  const auth = req.headers['authorization'];
  if (typeof auth === 'string') {
    const match = auth.match(/^Bearer\s+(\S+)$/i);
    if (match) {
      return match[1];
    }
  }
  return null;
}

/**
 * Validate that the inbound request carries the correct ephemeral proxy token.
 *
 * Returns true when the request should be allowed to proceed.
 * Returns false when the caller should send HTTP 401 and abort.
 *
 * Reads AWF_PROXY_TOKEN from process.env on each call so that the value
 * reflects the current environment (important for testability).
 * Uses timing-safe comparison to prevent token-oracle timing attacks.
 *
 * @param {import('http').IncomingMessage} req
 * @returns {boolean}
 */
function validateProxyAuth(req) {
  const expectedToken = process.env.AWF_PROXY_TOKEN || null;
  if (!expectedToken) {
    // Token not configured — reject all requests to enforce secure defaults.
    // This covers the case where the proxy is started without AWF_PROXY_TOKEN
    // (e.g., direct `docker run` without AWF CLI).
    return false;
  }
  const token = extractInboundToken(req);
  if (!token) {
    return false;
  }
  // Reject tokens of wrong length before the timing-safe compare to avoid
  // leaking length information via an early-exit exception from timingSafeEqual.
  if (token.length !== expectedToken.length) {
    return false;
  }
  try {
    return crypto.timingSafeEqual(Buffer.from(token), Buffer.from(expectedToken));
  } catch {
    return false;
  }
}

/**
 * Send a standardised HTTP 401 Unauthorized response.
 *
 * @param {import('http').ServerResponse} res
 * @param {string} requestId
 * @param {string} provider
 */
function rejectUnauthorized(res, requestId, provider) {
  logRequest('warn', 'auth_rejected', {
    request_id: requestId,
    provider,
    message: 'Request rejected: missing or invalid proxy authentication token',
  });
  metrics.increment('requests_total', { provider, method: 'UNKNOWN', status_class: '4xx' });
  if (!res.headersSent) {
    res.writeHead(401, {
      'Content-Type': 'application/json',
      'WWW-Authenticate': 'Bearer realm="awf-api-proxy"',
      'X-Request-ID': requestId,
    });
  }
  res.end(JSON.stringify({
    error: {
      type: 'authentication_error',
      message: 'Unauthorized: missing or invalid AWF proxy authentication token',
    },
  }));
}

// Configurable API target hosts (supports custom endpoints / internal LLM routers)
const OPENAI_API_TARGET = process.env.OPENAI_API_TARGET || 'api.openai.com';
const ANTHROPIC_API_TARGET = process.env.ANTHROPIC_API_TARGET || 'api.anthropic.com';

/**
 * Normalizes a base path for use as a URL path prefix.
 * Ensures the path starts with '/' (if non-empty) and has no trailing '/'.
 * Returns '' for empty, null, or undefined inputs.
 *
 * @param {string|undefined|null} rawPath - The raw path value from env or config
 * @returns {string} Normalized path prefix (e.g. '/serving-endpoints') or ''
 */
function normalizeBasePath(rawPath) {
  if (!rawPath) return '';
  let path = rawPath.trim();
  if (!path) return '';
  // Ensure leading slash
  if (!path.startsWith('/')) {
    path = '/' + path;
  }
  // Strip trailing slash (but preserve a bare '/')
  if (path !== '/' && path.endsWith('/')) {
    path = path.slice(0, -1);
  }
  return path;
}

/**
 * Build the full upstream path by joining basePath, reqUrl's pathname, and query string.
 *
 * Examples:
 *   buildUpstreamPath('/v1/chat/completions', 'api.openai.com', '')
 *     → '/v1/chat/completions'
 *   buildUpstreamPath('/v1/chat/completions', 'host.databricks.com', '/serving-endpoints')
 *     → '/serving-endpoints/v1/chat/completions'
 *   buildUpstreamPath('/v1/messages?stream=true', 'host.com', '/anthropic')
 *     → '/anthropic/v1/messages?stream=true'
 *
 * @param {string} reqUrl - The incoming request URL (must start with '/')
 * @param {string} targetHost - The upstream hostname (used only to parse the URL)
 * @param {string} basePath - Normalized base path prefix (e.g. '/serving-endpoints' or '')
 * @returns {string} Full upstream path including query string
 */
function buildUpstreamPath(reqUrl, targetHost, basePath) {
  const targetUrl = new URL(reqUrl, `https://${targetHost}`);
  const prefix = basePath === '/' ? '' : basePath;
  return prefix + targetUrl.pathname + targetUrl.search;
}

// Optional base path prefixes for API targets (e.g. /serving-endpoints for Databricks)
const OPENAI_API_BASE_PATH = normalizeBasePath(process.env.OPENAI_API_BASE_PATH);
const ANTHROPIC_API_BASE_PATH = normalizeBasePath(process.env.ANTHROPIC_API_BASE_PATH);

// Configurable Copilot API target host (supports GHES/GHEC / custom endpoints)
// Priority: COPILOT_API_TARGET env var > auto-derive from GITHUB_SERVER_URL > default
function deriveCopilotApiTarget() {
  if (process.env.COPILOT_API_TARGET) {
    return process.env.COPILOT_API_TARGET;
  }
  // Auto-derive from GITHUB_SERVER_URL:
  // - GitHub Enterprise Cloud (*.ghe.com): Copilot inference/models/MCP are served at
  //   copilot-api.<subdomain>.ghe.com (separate from the GitHub REST API at api.*)
  // - GitHub Enterprise Server (non-github.com, non-ghe.com) → api.enterprise.githubcopilot.com
  // - github.com → api.githubcopilot.com
  const serverUrl = process.env.GITHUB_SERVER_URL;
  if (serverUrl) {
    try {
      const hostname = new URL(serverUrl).hostname;
      if (hostname !== 'github.com') {
        // Check if this is a GHEC tenant (*.ghe.com)
        if (hostname.endsWith('.ghe.com')) {
          // Extract subdomain: mycompany.ghe.com → mycompany
          const subdomain = hostname.slice(0, -8); // Remove '.ghe.com'
          // GHEC routes Copilot inference to copilot-api.<subdomain>.ghe.com,
          // not to api.<subdomain>.ghe.com (which is the GitHub REST API)
          return `copilot-api.${subdomain}.ghe.com`;
        }
        // GHES (any other non-github.com hostname)
        return 'api.enterprise.githubcopilot.com';
      }
    } catch {
      // Invalid URL — fall through to default
    }
  }
  return 'api.githubcopilot.com';
}
const COPILOT_API_TARGET = deriveCopilotApiTarget();

// Squid proxy configuration (set via HTTP_PROXY/HTTPS_PROXY in docker-compose)
const HTTPS_PROXY = process.env.HTTPS_PROXY || process.env.HTTP_PROXY;

logRequest('info', 'startup', {
  message: 'Starting AWF API proxy sidecar',
  squid_proxy: HTTPS_PROXY || 'not configured',
  proxy_auth: AWF_PROXY_TOKEN ? 'enabled' : 'DISABLED (AWF_PROXY_TOKEN not set — all requests will be rejected)',
  api_targets: {
    openai: OPENAI_API_TARGET,
    anthropic: ANTHROPIC_API_TARGET,
    copilot: COPILOT_API_TARGET,
  },
  api_base_paths: {
    openai: OPENAI_API_BASE_PATH || '(none)',
    anthropic: ANTHROPIC_API_BASE_PATH || '(none)',
  },
  providers: {
    openai: !!OPENAI_API_KEY,
    anthropic: !!ANTHROPIC_API_KEY,
    copilot: !!COPILOT_GITHUB_TOKEN,
  },
});

if (!AWF_PROXY_TOKEN) {
  logRequest('error', 'startup', {
    message: 'AWF_PROXY_TOKEN is not configured. All non-health requests will be rejected with HTTP 401.',
  });
}

// Create proxy agent for routing through Squid
const proxyAgent = HTTPS_PROXY ? new HttpsProxyAgent(HTTPS_PROXY) : undefined;
if (!proxyAgent) {
  logRequest('warn', 'startup', { message: 'No HTTPS_PROXY configured, requests will go direct' });
}

/**
 * Check rate limit and send 429 if exceeded.
 * Returns true if request was rate-limited (caller should return early).
 */
function checkRateLimit(req, res, provider, requestBytes) {
  const check = limiter.check(provider, requestBytes);
  if (!check.allowed) {
    const clientRequestId = req.headers['x-request-id'];
    const requestId = (typeof clientRequestId === 'string' &&
      clientRequestId.length <= 128 &&
      /^[\w\-\.]+$/.test(clientRequestId))
      ? clientRequestId : generateRequestId();
    const limitLabels = { rpm: 'requests per minute', rph: 'requests per hour', bytes_pm: 'bytes per minute' };
    const windowLabel = limitLabels[check.limitType] || check.limitType;

    metrics.increment('rate_limit_rejected_total', { provider, limit_type: check.limitType });
    logRequest('warn', 'rate_limited', {
      request_id: requestId,
      provider,
      limit_type: check.limitType,
      limit: check.limit,
      retry_after: check.retryAfter,
    });

    res.writeHead(429, {
      'Content-Type': 'application/json',
      'Retry-After': String(check.retryAfter),
      'X-RateLimit-Limit': String(check.limit),
      'X-RateLimit-Remaining': String(check.remaining),
      'X-RateLimit-Reset': String(check.resetAt),
      'X-Request-ID': requestId,
    });
    res.end(JSON.stringify({
      error: {
        type: 'rate_limit_error',
        message: `Rate limit exceeded for ${provider} provider. Limit: ${check.limit} ${windowLabel}. Retry after ${check.retryAfter} seconds.`,
        provider,
        limit: check.limit,
        window: check.limitType === 'rpm' ? 'per_minute' : check.limitType === 'rph' ? 'per_hour' : 'per_minute_bytes',
        retry_after: check.retryAfter,
      },
    }));
    return true;
  }
  return false;
}

/**
 * Forward a request to the target API, injecting auth headers and routing through Squid.
 */
/** Validate that a request ID is safe (alphanumeric, dashes, dots, max 128 chars). */
function isValidRequestId(id) {
  return typeof id === 'string' && id.length <= 128 && /^[\w\-\.]+$/.test(id);
}

function proxyRequest(req, res, targetHost, injectHeaders, provider, basePath = '') {
  const clientRequestId = req.headers['x-request-id'];
  const requestId = isValidRequestId(clientRequestId) ? clientRequestId : generateRequestId();
  const startTime = Date.now();

  // Propagate request ID back to the client and forward to upstream
  res.setHeader('X-Request-ID', requestId);

  // Track active requests
  metrics.gaugeInc('active_requests', { provider });

  logRequest('info', 'request_start', {
    request_id: requestId,
    provider,
    method: req.method,
    path: sanitizeForLog(req.url),
    upstream_host: targetHost,
  });

  // Validate that req.url is a relative path (prevent open-redirect / SSRF)
  if (!req.url || !req.url.startsWith('/')) {
    const duration = Date.now() - startTime;
    metrics.gaugeDec('active_requests', { provider });
    metrics.increment('requests_total', { provider, method: req.method, status_class: '4xx' });
    logRequest('warn', 'request_complete', {
      request_id: requestId,
      provider,
      method: req.method,
      path: sanitizeForLog(req.url),
      status: 400,
      duration_ms: duration,
      upstream_host: targetHost,
    });
    res.writeHead(400, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Bad Request', message: 'URL must be a relative path' }));
    return;
  }

  // Build target URL
  const upstreamPath = buildUpstreamPath(req.url, targetHost, basePath);

  // Handle client-side errors (e.g. aborted connections)
  req.on('error', (err) => {
    if (errored) return; // Prevent double handling
    errored = true;
    const duration = Date.now() - startTime;
    metrics.gaugeDec('active_requests', { provider });
    metrics.increment('requests_errors_total', { provider });
    logRequest('error', 'request_error', {
      request_id: requestId,
      provider,
      method: req.method,
      path: sanitizeForLog(req.url),
      duration_ms: duration,
      error: sanitizeForLog(err.message),
      upstream_host: targetHost,
    });
    if (!res.headersSent) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
    }
    res.end(JSON.stringify({ error: 'Client error', message: err.message }));
  });

  // Read the request body with size limit
  const chunks = [];
  let totalBytes = 0;
  let rejected = false;
  let errored = false;

  req.on('data', chunk => {
    if (rejected || errored) return;
    totalBytes += chunk.length;
    if (totalBytes > MAX_BODY_SIZE) {
      rejected = true;
      const duration = Date.now() - startTime;
      metrics.gaugeDec('active_requests', { provider });
      metrics.increment('requests_total', { provider, method: req.method, status_class: '4xx' });
      logRequest('warn', 'request_complete', {
        request_id: requestId,
        provider,
        method: req.method,
        path: sanitizeForLog(req.url),
        status: 413,
        duration_ms: duration,
        request_bytes: totalBytes,
        upstream_host: targetHost,
      });
      if (!res.headersSent) {
        res.writeHead(413, { 'Content-Type': 'application/json' });
      }
      res.end(JSON.stringify({ error: 'Payload Too Large', message: 'Request body exceeds 10 MB limit' }));
      return;
    }
    chunks.push(chunk);
  });

  req.on('end', () => {
    if (rejected || errored) return;
    const body = Buffer.concat(chunks);
    const requestBytes = body.length;

    metrics.increment('request_bytes_total', { provider }, requestBytes);

    // Copy incoming headers, stripping sensitive/proxy headers, then inject auth
    const headers = {};
    for (const [name, value] of Object.entries(req.headers)) {
      if (!shouldStripHeader(name)) {
        headers[name] = value;
      }
    }
    // Ensure X-Request-ID is forwarded to upstream
    headers['x-request-id'] = requestId;
    Object.assign(headers, injectHeaders);

    const options = {
      hostname: targetHost,
      port: 443,
      path: upstreamPath,
      method: req.method,
      headers,
      agent: proxyAgent, // Route through Squid
    };

    const proxyReq = https.request(options, (proxyRes) => {
      let responseBytes = 0;

      proxyRes.on('data', (chunk) => {
        responseBytes += chunk.length;
      });

      // Handle response stream errors
      proxyRes.on('error', (err) => {
        const duration = Date.now() - startTime;
        metrics.gaugeDec('active_requests', { provider });
        metrics.increment('requests_errors_total', { provider });
        logRequest('error', 'request_error', {
          request_id: requestId,
          provider,
          method: req.method,
          path: sanitizeForLog(req.url),
          duration_ms: duration,
          error: sanitizeForLog(err.message),
          upstream_host: targetHost,
        });
        if (!res.headersSent) {
          res.writeHead(502, { 'Content-Type': 'application/json' });
        }
        res.end(JSON.stringify({ error: 'Response stream error', message: err.message }));
      });

      proxyRes.on('end', () => {
        const duration = Date.now() - startTime;
        const sc = metrics.statusClass(proxyRes.statusCode);
        metrics.gaugeDec('active_requests', { provider });
        metrics.increment('requests_total', { provider, method: req.method, status_class: sc });
        metrics.increment('response_bytes_total', { provider }, responseBytes);
        metrics.observe('request_duration_ms', duration, { provider });

        logRequest('info', 'request_complete', {
          request_id: requestId,
          provider,
          method: req.method,
          path: sanitizeForLog(req.url),
          status: proxyRes.statusCode,
          duration_ms: duration,
          request_bytes: requestBytes,
          response_bytes: responseBytes,
          upstream_host: targetHost,
        });
      });

      // Copy response headers and add X-Request-ID
      const resHeaders = { ...proxyRes.headers, 'x-request-id': requestId };
      res.writeHead(proxyRes.statusCode, resHeaders);
      proxyRes.pipe(res);
    });

    proxyReq.on('error', (err) => {
      const duration = Date.now() - startTime;
      metrics.gaugeDec('active_requests', { provider });
      metrics.increment('requests_errors_total', { provider });
      metrics.increment('requests_total', { provider, method: req.method, status_class: '5xx' });
      metrics.observe('request_duration_ms', duration, { provider });

      logRequest('error', 'request_error', {
        request_id: requestId,
        provider,
        method: req.method,
        path: sanitizeForLog(req.url),
        duration_ms: duration,
        error: sanitizeForLog(err.message),
        upstream_host: targetHost,
      });
      if (!res.headersSent) {
        res.writeHead(502, { 'Content-Type': 'application/json' });
      }
      res.end(JSON.stringify({ error: 'Proxy error', message: err.message }));
    });

    if (body.length > 0) {
      proxyReq.write(body);
    }
    proxyReq.end();
  });
}

/**
 * Build the enhanced health response (superset of original format).
 */
function healthResponse() {
  return {
    status: 'healthy',
    service: 'awf-api-proxy',
    squid_proxy: HTTPS_PROXY || 'not configured',
    providers: {
      openai: !!OPENAI_API_KEY,
      anthropic: !!ANTHROPIC_API_KEY,
      copilot: !!COPILOT_GITHUB_TOKEN,
    },
    metrics_summary: metrics.getSummary(),
    rate_limits: limiter.getAllStatus(),
  };
}

/**
 * Handle management endpoints on port 10000 (/health, /metrics).
 * Returns true if the request was handled, false otherwise.
 */
function handleManagementEndpoint(req, res) {
  if (req.method === 'GET' && req.url === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(healthResponse()));
    return true;
  }
  if (req.method === 'GET' && req.url === '/metrics') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(metrics.getMetrics()));
    return true;
  }
  return false;
}

// Only start the server if this file is run directly (not imported for testing)
if (require.main === module) {
  // Health port is always 10000 — this is what Docker healthcheck hits
  const HEALTH_PORT = 10000;

  // OpenAI API proxy (port 10000)
  if (OPENAI_API_KEY) {
    const server = http.createServer((req, res) => {
      if (handleManagementEndpoint(req, res)) return;
      const requestId = generateRequestId();
      if (!validateProxyAuth(req)) {
        rejectUnauthorized(res, requestId, 'openai');
        return;
      }
      const contentLength = parseInt(req.headers['content-length'], 10) || 0;
      if (checkRateLimit(req, res, 'openai', contentLength)) return;

      proxyRequest(req, res, OPENAI_API_TARGET, {
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
      }, 'openai', OPENAI_API_BASE_PATH);
    });

    server.listen(HEALTH_PORT, '0.0.0.0', () => {
      logRequest('info', 'server_start', { message: `OpenAI proxy listening on port ${HEALTH_PORT}`, target: OPENAI_API_TARGET });
    });
  } else {
    // No OpenAI key — still need a health endpoint on port 10000 for Docker healthcheck
    const server = http.createServer((req, res) => {
      if (handleManagementEndpoint(req, res)) return;

      res.writeHead(404, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'OpenAI proxy not configured (no OPENAI_API_KEY)' }));
    });

    server.listen(HEALTH_PORT, '0.0.0.0', () => {
      logRequest('info', 'server_start', { message: `Health endpoint listening on port ${HEALTH_PORT} (OpenAI not configured)` });
    });
  }

  // Anthropic API proxy (port 10001)
  if (ANTHROPIC_API_KEY) {
    const server = http.createServer((req, res) => {
      if (req.url === '/health' && req.method === 'GET') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ status: 'healthy', service: 'anthropic-proxy' }));
        return;
      }

      const requestId = generateRequestId();
      if (!validateProxyAuth(req)) {
        rejectUnauthorized(res, requestId, 'anthropic');
        return;
      }

      const contentLength = parseInt(req.headers['content-length'], 10) || 0;
      if (checkRateLimit(req, res, 'anthropic', contentLength)) return;

      // Only set anthropic-version as default; preserve agent-provided version
      const anthropicHeaders = { 'x-api-key': ANTHROPIC_API_KEY };
      if (!req.headers['anthropic-version']) {
        anthropicHeaders['anthropic-version'] = '2023-06-01';
      }
      proxyRequest(req, res, ANTHROPIC_API_TARGET, anthropicHeaders, 'anthropic', ANTHROPIC_API_BASE_PATH);
    });

    server.listen(10001, '0.0.0.0', () => {
      logRequest('info', 'server_start', { message: 'Anthropic proxy listening on port 10001', target: ANTHROPIC_API_TARGET });
    });
  }


  // GitHub Copilot API proxy (port 10002)
  if (COPILOT_GITHUB_TOKEN) {
    const copilotServer = http.createServer((req, res) => {
      // Health check endpoint
      if (req.url === '/health' && req.method === 'GET') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ status: 'healthy', service: 'copilot-proxy' }));
        return;
      }

      const requestId = generateRequestId();
      if (!validateProxyAuth(req)) {
        rejectUnauthorized(res, requestId, 'copilot');
        return;
      }

      const contentLength = parseInt(req.headers['content-length'], 10) || 0;
      if (checkRateLimit(req, res, 'copilot', contentLength)) return;

      proxyRequest(req, res, COPILOT_API_TARGET, {
        'Authorization': `Bearer ${COPILOT_GITHUB_TOKEN}`,
      }, 'copilot');
    });

    copilotServer.listen(10002, '0.0.0.0', () => {
      logRequest('info', 'server_start', { message: 'GitHub Copilot proxy listening on port 10002' });
    });
  }

  // OpenCode API proxy (port 10004) — routes to Anthropic (default BYOK provider)
  // OpenCode gets a separate port from Claude (10001) for per-engine rate limiting,
  // metrics isolation, and future provider routing (OpenCode is BYOK and may route
  // to different providers in the future based on model prefix).
  if (ANTHROPIC_API_KEY) {
    const opencodeServer = http.createServer((req, res) => {
      if (req.url === '/health' && req.method === 'GET') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ status: 'healthy', service: 'opencode-proxy' }));
        return;
      }

      const requestId = generateRequestId();
      if (!validateProxyAuth(req)) {
        rejectUnauthorized(res, requestId, 'opencode');
        return;
      }

      const logMethod = sanitizeForLog(req.method);
      const logUrl = sanitizeForLog(req.url);
      logRequest('info', 'opencode_proxy_request', {
        message: '[OpenCode Proxy] Incoming request',
        method: logMethod,
        url: logUrl,
      });
      logRequest('info', 'opencode_proxy_header_injection', {
        message: '[OpenCode Proxy] Injecting x-api-key header with ANTHROPIC_API_KEY',
      });
      const anthropicHeaders = { 'x-api-key': ANTHROPIC_API_KEY };
      if (!req.headers['anthropic-version']) {
        anthropicHeaders['anthropic-version'] = '2023-06-01';
      }
      proxyRequest(req, res, ANTHROPIC_API_TARGET, anthropicHeaders);
    });

    opencodeServer.listen(10004, '0.0.0.0', () => {
      console.log(`[API Proxy] OpenCode proxy listening on port 10004 (-> Anthropic at ${ANTHROPIC_API_TARGET})`);
    });
  }

  // Graceful shutdown
  process.on('SIGTERM', () => {
    logRequest('info', 'shutdown', { message: 'Received SIGTERM, shutting down gracefully' });
    process.exit(0);
  });

  process.on('SIGINT', () => {
    logRequest('info', 'shutdown', { message: 'Received SIGINT, shutting down gracefully' });
    process.exit(0);
  });
}

// Export for testing
module.exports = { deriveCopilotApiTarget, normalizeBasePath, buildUpstreamPath, extractInboundToken, validateProxyAuth };
