import { detectHostDnsServers, DEFAULT_DNS_SERVERS, filterForNetworkIsolation } from './dns-resolver';
import * as fs from 'fs';

jest.mock('fs');
const mockedFs = fs as jest.Mocked<typeof fs>;

const mockLogger = {
  debug: jest.fn(),
  info: jest.fn(),
  warn: jest.fn(),
  error: jest.fn(),
  success: jest.fn(),
  setLevel: jest.fn(),
};

beforeEach(() => {
  jest.clearAllMocks();
});

describe('parseResolvConf (via detectHostDnsServers)', () => {
  it('extracts nameservers from standard content', () => {
    mockedFs.readFileSync.mockReturnValue(`# Generated by systemd-resolved
nameserver 1.1.1.1
nameserver 9.9.9.9
search example.com
`);
    expect(detectHostDnsServers(mockLogger as any)).toEqual(['1.1.1.1', '9.9.9.9']);
  });

  it('ignores comments and empty lines', () => {
    mockedFs.readFileSync.mockReturnValue(`
# This is a comment
; Another comment style

nameserver 1.1.1.1

# nameserver 2.2.2.2
nameserver 8.8.8.8
`);
    expect(detectHostDnsServers(mockLogger as any)).toEqual(['1.1.1.1', '8.8.8.8']);
  });

  it('skips invalid IPs', () => {
    mockedFs.readFileSync.mockReturnValue(`nameserver 1.1.1.1
nameserver not-an-ip
nameserver 8.8.8.8
`);
    expect(detectHostDnsServers(mockLogger as any)).toEqual(['1.1.1.1', '8.8.8.8']);
  });

  it('handles IPv6 nameservers (loopback filtered by detectHostDnsServers)', () => {
    mockedFs.readFileSync.mockReturnValue(`nameserver 2001:4860:4860::8888
nameserver 1.1.1.1
nameserver ::1
`);
    // ::1 is loopback so detectHostDnsServers filters it out
    expect(detectHostDnsServers(mockLogger as any)).toEqual(['2001:4860:4860::8888', '1.1.1.1']);
  });
});

describe('detectHostDnsServers', () => {
  it('filters out 127.0.0.11 (Docker embedded DNS)', () => {
    mockedFs.readFileSync.mockReturnValue(
      'nameserver 127.0.0.11\nnameserver 1.1.1.1\nnameserver 8.8.8.8\n'
    );
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(['1.1.1.1', '8.8.8.8']);
  });

  it('filters out 127.0.0.53 and tries secondary file', () => {
    mockedFs.readFileSync.mockImplementation((filePath: any) => {
      if (filePath === '/run/systemd/resolve/resolv.conf') {
        throw new Error('ENOENT');
      }
      if (filePath === '/etc/resolv.conf') {
        return 'nameserver 127.0.0.53\n';
      }
      throw new Error('ENOENT');
    });
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(DEFAULT_DNS_SERVERS);
    expect(mockLogger.warn).toHaveBeenCalled();
  });

  it('returns DEFAULT_DNS_SERVERS when no files are readable', () => {
    mockedFs.readFileSync.mockImplementation(() => {
      throw new Error('ENOENT');
    });
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(DEFAULT_DNS_SERVERS);
    expect(mockLogger.warn).toHaveBeenCalledWith(
      expect.stringContaining('falling back to')
    );
  });

  it('uses first readable file with usable servers', () => {
    mockedFs.readFileSync.mockImplementation((filePath: any) => {
      if (filePath === '/run/systemd/resolve/resolv.conf') {
        return 'nameserver 9.9.9.9\nnameserver 1.1.1.1\n';
      }
      return 'nameserver 8.8.8.8\n';
    });
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(['9.9.9.9', '1.1.1.1']);
    expect(mockLogger.info).toHaveBeenCalledWith(
      expect.stringContaining('/run/systemd/resolve/resolv.conf')
    );
  });

  it('filters out ::1 IPv6 loopback', () => {
    mockedFs.readFileSync.mockReturnValue(
      'nameserver ::1\nnameserver 2001:4860:4860::8888\n'
    );
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(['2001:4860:4860::8888']);
  });
});

describe('DEFAULT_DNS_SERVERS', () => {
  it('should have correct default DNS servers', () => {
    expect(DEFAULT_DNS_SERVERS).toEqual(['8.8.8.8', '8.8.4.4']);
  });
});

describe('filterForNetworkIsolation', () => {
  it('returns public DNS servers unchanged', async () => {
    const result = await filterForNetworkIsolation(['8.8.8.8', '8.8.4.4'], mockLogger as any);
    expect(result).toEqual(['8.8.8.8', '8.8.4.4']);
    expect(mockLogger.warn).not.toHaveBeenCalled();
  });

  it('preserves Azure DHCP DNS in network-isolation mode', async () => {
    const result = await filterForNetworkIsolation(['168.63.129.16'], mockLogger as any);
    expect(result).toEqual(['168.63.129.16']);
    expect(mockLogger.warn).not.toHaveBeenCalled();
  });

  it('preserves Tailscale Magic DNS in network-isolation mode', async () => {
    const result = await filterForNetworkIsolation(['100.100.100.100'], mockLogger as any);
    expect(result).toEqual(['100.100.100.100']);
    expect(mockLogger.warn).not.toHaveBeenCalled();
  });

  it('preserves link-local DNS addresses', async () => {
    const result = await filterForNetworkIsolation(['169.254.1.1'], mockLogger as any);
    expect(result).toEqual(['169.254.1.1']);
    expect(mockLogger.warn).not.toHaveBeenCalled();
  });

  it('preserves GKE NodeLocal DNS', async () => {
    const result = await filterForNetworkIsolation(['169.254.20.10'], mockLogger as any);
    expect(result).toEqual(['169.254.20.10']);
    expect(mockLogger.warn).not.toHaveBeenCalled();
  });

  it('preserves mixed resolver lists without substituting public DNS', async () => {
    const result = await filterForNetworkIsolation(
      ['168.63.129.16', '8.8.8.8', '1.1.1.1'],
      mockLogger as any
    );
    expect(result).toEqual(['168.63.129.16', '8.8.8.8', '1.1.1.1']);
    expect(mockLogger.warn).not.toHaveBeenCalled();
  });

  it('keeps RFC1918 corporate DNS servers intact', async () => {
    const result = await filterForNetworkIsolation(
      ['10.0.0.1', '192.168.1.1'],
      mockLogger as any
    );
    expect(result).toEqual(['10.0.0.1', '192.168.1.1']);
    expect(mockLogger.warn).not.toHaveBeenCalled();
  });

  it('uses default logger when no logger is provided', async () => {
    // Should not throw when called without a logger
    await expect(filterForNetworkIsolation(['8.8.8.8'])).resolves.toEqual(['8.8.8.8']);
  });
});
