/**
 * Runtime config validation using the published JSON Schema.
 *
 * The schema JSON is loaded from disk so the emitted JS does not contain a
 * fragile runtime `require('./awf-config-schema.json')`. The canonical source
 * is generated by `scripts/generate-schema.mjs` and kept in sync via CI.
 */

import Ajv2020, { ErrorObject } from 'ajv/dist/2020';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

function loadSchema(): Record<string, unknown> {
  const candidatePaths = [
    join(__dirname, 'awf-config-schema.json'),
    join(__dirname, '../src/awf-config-schema.json'),
  ];

  for (const candidatePath of candidatePaths) {
    if (existsSync(candidatePath)) {
      return JSON.parse(readFileSync(candidatePath, 'utf8')) as Record<string, unknown>;
    }
  }

  throw new Error(
    `Unable to locate awf-config-schema.json. Checked: ${candidatePaths.join(', ')}`,
  );
}

// Compile once (module-level singleton). allErrors collects every violation.
// verbose=true provides parentSchema on errors for richer formatting.
const ajv = new Ajv2020({ allErrors: true, verbose: true });
const validate = ajv.compile(loadSchema());

/**
 * Check if a schema path points to an array-of-strings field by inspecting
 * the parent schema context.
 */
function isArrayOfStringsField(err: ErrorObject): boolean {
  // When type=array fails, check if the schema also specifies items.type=string
  if (err.keyword === 'type' && err.params.type === 'array') {
    const parentSchema = err.parentSchema as Record<string, unknown> | undefined;
    if (parentSchema) {
      const items = parentSchema.items as Record<string, unknown> | undefined;
      if (items && items.type === 'string') {
        return true;
      }
    }
  }
  return false;
}

/**
 * Check if an integer field also has minimum:1 constraint (making it "positive integer").
 */
function hasMinimumOne(err: ErrorObject): boolean {
  const parentSchema = err.parentSchema as Record<string, unknown> | undefined;
  return parentSchema?.minimum === 1;
}

/**
 * Format a single ajv error into a human-readable string matching the
 * style of the previous hand-written validator (e.g. "config.network.allowDomains must be ...").
 */
function formatError(err: ErrorObject): string {
  const path = err.instancePath
    ? 'config' + err.instancePath.replace(/\//g, '.')
    : 'config';

  switch (err.keyword) {
    case 'type':
      if (err.params.type === 'array' && isArrayOfStringsField(err)) {
        return `${path} must be an array of strings`;
      }
      if (err.params.type === 'integer') {
        return hasMinimumOne(err)
          ? `${path} must be a positive integer`
          : `${path} must be an integer`;
      }
      return `${path} must be ${err.params.type === 'object' ? 'an object' : determineArticle(err.params.type) + err.params.type}`;

    case 'additionalProperties':
      return `${path}.${err.params.additionalProperty} is not supported`;

    case 'enum':
      return `${path} must be one of: ${(err.params.allowedValues as string[]).join(', ')}`;

    case 'minimum':
      return `${path} must be a positive integer`;

    case 'oneOf':
      return `${path} must be a string or array of strings`;

    case 'items':
      return `${path} must be an array of strings`;

    default:
      return `${path} ${err.message || 'is invalid'}`;
  }
}

function determineArticle(type: string): string {
  return /^[aeiou]/i.test(type) ? 'an ' : 'a ';
}

/**
 * Deduplicate and simplify errors. Ajv often emits multiple errors for one
 * conceptual issue (e.g. oneOf failures emit sub-schema failures + the oneOf itself).
 * Also consolidates per-item errors into a single array-level message.
 */
function deduplicateErrors(errors: ErrorObject[]): ErrorObject[] {
  const oneOfPaths = new Set<string>();
  const result: ErrorObject[] = [];

  // First pass: collect oneOf paths
  for (const err of errors) {
    if (err.keyword === 'oneOf') {
      oneOfPaths.add(err.instancePath);
    }
  }

  // Track which array paths we've already emitted a consolidated message for
  const emittedArrayErrors = new Set<string>();

  // Second pass: filter and consolidate
  for (const err of errors) {
    // Skip sub-errors of oneOf (they are noise)
    if (oneOfPaths.has(err.instancePath) && err.keyword !== 'oneOf') {
      continue;
    }

    // Consolidate per-item type errors into a single "must be an array of strings"
    if (err.keyword === 'type' && /\/\d+$/.test(err.instancePath)) {
      const parentPath = err.instancePath.replace(/\/\d+$/, '');
      if (!emittedArrayErrors.has(parentPath)) {
        emittedArrayErrors.add(parentPath);
        // Create a synthetic error for the parent path
        result.push({
          ...err,
          instancePath: parentPath,
          keyword: 'items',
          message: 'must be an array of strings',
        });
      }
      continue;
    }

    result.push(err);
  }

  return result;
}

/**
 * Validate an unknown value against the AWF config schema.
 * Returns an array of human-readable error strings (empty = valid).
 */
export function validateWithSchema(config: unknown): string[] {
  // Handle non-object root specially for a cleaner message
  if (typeof config !== 'object' || config === null || Array.isArray(config)) {
    return ['config root must be an object'];
  }

  const valid = validate(config);
  if (valid || !validate.errors) {
    return [];
  }

  const deduplicated = deduplicateErrors(validate.errors);
  return deduplicated.map(formatError);
}
